import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider, AddTaskProvider } from "./context";
import { CookiesProvider } from "next-client-cookies/server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AddTaskProvider>
        <UserProvider>
          <CookiesProvider>
            <body className={inter.className}>{children}</body>
          </CookiesProvider>
        </UserProvider>
      </AddTaskProvider>
    </html>
  );
}
